#include "logic.h"
#include "draw.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
//FIXME: #include "garbage.h"
#include "player.h"
#include "screens.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "game.h"

// AppState enum definition
typedef enum
{
    // TA-TODO: Add any additional states you need for your app.
    START,
    START_NODRAW,
    APP_INIT,
    APP,
    APP_EXIT,
    APP_EXIT_NODRAW,
} GBAState;

int main(void)
{
    hardware_video_init();
    GBAState state = START;

    // We store the "previous" and "current" states.
    AppState currentAppState, nextAppState;

    // We store the current and previous values of the button input.
    uint32_t previousButtons = BUTTONS;
    uint32_t currentButtons = BUTTONS;

    while( 1 )
    {
        // Load the current state of the buttons
        currentButtons = BUTTONS;

        // TA-TODO: Manipulate the state machine below as needed.
        switch( state )
        {
        case START:
            // Wait for VBlank
            waitForVBlank();

            // TA-TODO: Draw the start state here.
            drawFullScreenImageDMA( background );
            // drawImageDMA(10, 10, SHIP_WIDTH, SHIP_HEIGHT, ship);
            // drawImageDMA(10, 10, GARBAGE_WIDTH, GARBAGE_HEIGHT, garbage);
            state = APP_INIT; // START_NODRAW;
            break;

        case START_NODRAW:
            // TA-TODO: Check for a button press here to start the app.
            // Start the app by switching the state to APP_INIT.
            if( KEY_JUST_PRESSED( BUTTON_A, currentButtons, previousButtons ) )
            {
                state = APP_INIT;
            }
            break;

        case APP_INIT:
            // Initialize the app. Switch to the APP state.
            initializeAppState( &currentAppState );

            // Draw the initial state of the app
            fullDrawAppState( &currentAppState );
            // fillScreenDMA(GRAY);
            state = APP;
            break;

        case APP:
            // Process the app for one frame, store the next state
            nextAppState = processAppState( &currentAppState, previousButtons, currentButtons );

            // Wait for VBlank before we do any drawing.
            waitForVBlank();

            // Undraw the previous state
            undrawAppState( &currentAppState );

            // Draw the current state
            drawAppState( &nextAppState );
            // drawImageDMA(nextAppState.p.x, nextAppState.p.y, SHIP_WIDTH, SHIP_HEIGHT, ship);
            // Now set the current state as the next state for the next iter.
            currentAppState = nextAppState;

            // Check if the app is exiting. If it is, then go to the exit state.
            if( nextAppState.gameOver )
            {
                state = APP_EXIT;
            }
            if( KEY_JUST_PRESSED( BUTTON_SELECT, currentButtons, previousButtons ) )
            {
                state = START;
            }
            break;

        case APP_EXIT:
            // Wait for VBlank
            waitForVBlank();

            // TA-TODO: Draw the exit / gameover screen
            char *result;
            uint16_t c;
            if( nextAppState.gameOver == 1 )
            {
                fillScreenDMA( BLACK );
                result = "You Lost";
                c = RED;
            }
            else
            {
                fillScreenDMA( GREEN );
                result = "You Won!";
                c = BLACK;
            }
            char *message1 = "Press select to return to";
            char *message2 = "the start screen";
            drawString( 70, WIDTH / 2 - (3 * strlen( result )), result, c );
            drawString( 100, WIDTH / 2 - (3 * strlen( message1 )), message1, c );
            drawString( 110, WIDTH / 2 - (3 * strlen( message2 )), message2, c );
            state = APP_EXIT_NODRAW;
            break;

        case APP_EXIT_NODRAW:
            // TA-TODO: Check for a button press here to go back to the start screen
            if( KEY_JUST_PRESSED( BUTTON_SELECT, currentButtons, previousButtons ) )
            {
                state = START;
            }
            break;
        }

        // Store the current state of the buttons
        previousButtons = currentButtons;
    }

    return 0;
}
